In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
df = pd.read_csv("4-Algerian_forest_fires_dataset.csv")

In [3]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    object
 3   Temperature  245 non-null    object
 4    RH          245 non-null    object
 5    Ws          245 non-null    object
 6   Rain         245 non-null    object
 7   FFMC         245 non-null    object
 8   DMC          245 non-null    object
 9   DC           245 non-null    object
 10  ISI          245 non-null    object
 11  BUI          245 non-null    object
 12  FWI          245 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 27.1+ KB

In [5]:
df.isnull().sum()

day            1
month          2
year           2
Temperature    2
 RH            2
 Ws            2
Rain           2
FFMC           2
DMC            2
DC             2
ISI            2
BUI            2
FWI            2
Classes        3
dtype: int64

In [6]:
df_copy = df.copy()

In [7]:
df_copy = df_copy.dropna().reset_index(drop=True)

In [8]:
df_copy

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
240,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
241,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
242,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
243,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [9]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    object
 1   month        244 non-null    object
 2   year         244 non-null    object
 3   Temperature  244 non-null    object
 4    RH          244 non-null    object
 5    Ws          244 non-null    object
 6   Rain         244 non-null    object
 7   FFMC         244 non-null    object
 8   DMC          244 non-null    object
 9   DC           244 non-null    object
 10  ISI          244 non-null    object
 11  BUI          244 non-null    object
 12  FWI          244 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 26.8+ KB

In [10]:
df_copy["day"].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', 'day'],
      dtype=object)

In [11]:
df_copy[df_copy["day"]=="day"]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes

In [12]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    object
 1   month        244 non-null    object
 2   year         244 non-null    object
 3   Temperature  244 non-null    object
 4    RH          244 non-null    object
 5    Ws          244 non-null    object
 6   Rain         244 non-null    object
 7   FFMC         244 non-null    object
 8   DMC          244 non-null    object
 9   DC           244 non-null    object
 10  ISI          244 non-null    object
 11  BUI          244 non-null    object
 12  FWI          244 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 26.8+ KB

In [13]:
df_copy.reset_index()

,index,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
240,240,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
241,241,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
242,242,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
243,243,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [14]:
df_copy.iloc[122]

day                    day
month                month
year                  year
Temperature    Temperature
 RH                     RH
 Ws                     Ws
Rain                 Rain
FFMC                  FFMC
DMC                    DMC
DC                      DC
ISI                    ISI
BUI                    BUI
FWI                    FWI
Classes          Classes
Name: 122, dtype: object

In [15]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  '],
      dtype='object')

In [16]:
df_copy.columns = df_copy.columns.str.strip()

In [17]:
df_copy["Temperature"].unique()

array(['29', '26', '25', '27', '31', '33', '30', '28', '32', '34', '35',
       '36', '37', '22', '24', 'Temperature', '38', '39', '40', '42'],
      dtype=object)

In [18]:
df_copy = df_copy.drop(122)

In [19]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    object
 1   month        243 non-null    object
 2   year         243 non-null    object
 3   Temperature  243 non-null    object
 4   RH           243 non-null    object
 5   Ws           243 non-null    object
 6   Rain         243 non-null    object
 7   FFMC         243 non-null    object
 8   DMC          243 non-null    object
 9   DC           243 non-null    object
 10  ISI          243 non-null    object
 11  BUI          243 non-null    object
 12  FWI          243 non-null    object
 13  Classes      243 non-null    object
dtypes: object(14)
memory usage: 28.5+ KB

In [20]:
df_copy.reset_index()

,index,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,239,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
239,240,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
240,241,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
241,242,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
242,243,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [21]:
df_copy[["Temperature","RH","Ws"]] = df_copy[["Temperature","RH","Ws"]].astype(int)

In [22]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    object
 1   month        243 non-null    object
 2   year         243 non-null    object
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    object
 7   FFMC         243 non-null    object
 8   DMC          243 non-null    object
 9   DC           243 non-null    object
 10  ISI          243 non-null    object
 11  BUI          243 non-null    object
 12  FWI          243 non-null    object
 13  Classes      243 non-null    object
dtypes: int64(3), object(11)
memory usage: 28.5+ KB

In [23]:
df_copy = df_copy.drop(columns=["day","month","year"])

In [24]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  243 non-null    int64
 1   RH           243 non-null    int64
 2   Ws           243 non-null    int64
 3   Rain         243 non-null    object
 4   FFMC         243 non-null    object
 5   DMC          243 non-null    object
 6   DC           243 non-null    object
 7   ISI          243 non-null    object
 8   BUI          243 non-null    object
 9   FWI          243 non-null    object
 10  Classes      243 non-null    object
dtypes: int64(3), object(8)
memory usage: 22.8+ KB

In [25]:
df_copy[["Rain","FFMC","DMC","DC","ISI","BUI","FWI"]] = df_copy[["Rain","FFMC","DMC","DC","ISI","BUI","FWI"]].astype(float)

In [26]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  243 non-null    int64
 1   RH           243 non-null    int64
 2   Ws           243 non-null    int64
 3   Rain         243 non-null    float64
 4   FFMC         243 non-null    float64
 5   DMC          243 non-null    float64
 6   DC           243 non-null    float64
 7   ISI          243 non-null    float64
 8   BUI          243 non-null    float64
 9   FWI          243 non-null    float64
 10  Classes      243 non-null    object
dtypes: float64(7), int64(3), object(1)
memory usage: 22.8+ KB

In [30]:
df_copy["Classes"].unique()

array(['not fire   ', 'fire   ', 'fire', 'fire ', 'not fire', 'not fire ',
       'not fire     ', 'not fire    '], dtype=object)

In [31]:
df_copy["Classes"] = np.where(df_copy["Classes"].str.contains("not fire"), 0,1)

In [32]:
df_copy

     Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI  Classes
0             29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5        0
1             29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4        0
2             26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1        0
3             25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0        0
4             27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5        0
..           ...  ..  ..   ...   ...   ...   ...  ...   ...  ...      ...
239           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5        1
240           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0        0
241           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2        0
242           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7        0
243           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5        0

[243 rows x 11 columns]

In [33]:
df_copy["Classes"].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64

In [34]:
X=df_copy[["Temperature","RH","Ws","Rain","FFMC","DMC","DC","ISI","BUI"]]
y= df_copy["FWI"]

In [35]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

In [39]:
scaler = StandardScaler()

In [40]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [41]:
model = LinearRegression()

In [42]:
model.fit(X_train_scaled,y_train)

LinearRegression()

In [43]:
y_pred = model.predict(X_test_scaled)

In [44]:
print("R2 Score" , r2_score(y_test,y_pred))

R2 Score 0.9882600666169832

In [45]:
#Ridge

In [46]:
from sklearn.linear_model import Ridge

In [47]:
ridge = Ridge()

In [48]:
ridge.fit(X_train_scaled,y_train)

Ridge()

In [49]:
y_pred = ridge.predict(X_test_scaled)

In [50]:
print("R2 : ",r2_score(y_test,y_pred))

R2 :  0.9856164516456895

In [51]:
#Lasso

In [52]:
from sklearn.linear_model import Lasso

In [53]:
lasso = Lasso()

In [54]:
lasso.fit(X_train_scaled,y_train)

Lasso()

In [55]:
y_pred = lasso.predict(X_test_scaled)

In [56]:
print("R2 : ",r2_score(y_test,y_pred))

R2 :  0.9548117077009715

In [57]:
#Elastic

In [58]:
from sklearn.linear_model import ElasticNet

In [59]:
elastic = ElasticNet()

In [60]:
elastic.fit(X_train_scaled,y_train)

ElasticNet()

In [61]:
y_pred = elastic.predict(X_test_scaled)

In [62]:
print("R2 : ",r2_score(y_test,y_pred))

R2 :  0.8938926858602645

In [63]:
#CROSS VALİDATİON

In [64]:
from sklearn.linear_model import RidgeCV

In [66]:
ridgecv = RidgeCV()

In [67]:
ridgecv.fit(X_train_scaled,y_train)

RidgeCV()

In [68]:
y_pred = ridgecv.predict(X_test_scaled)

In [69]:
print("R2 : ",r2_score(y_test,y_pred))

R2 :  0.9856164516456933

In [70]:
from sklearn.linear_model import ElasticNetCV

In [71]:
elasticnetcv = ElasticNetCV()

In [72]:
elasticnetcv.fit(X_train_scaled,y_train)

ElasticNetCV()

In [73]:
y_pred = elasticnetcv.predict(X_test_scaled)

In [74]:
print("R2 : ",r2_score(y_test,y_pred))

R2 :  0.9810654492310573